platform :ios, '14.0'

# Disable CocoaPods stats to reduce build latency
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Define the Xcode project
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# Load Flutter's CocoaPods helper
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Set up Flutter iOS pods
flutter_ios_podfile_setup

# Define the Runner target
target 'Runner' do
  use_frameworks!

  # Specify modular headers for Firebase dependencies
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Auth', :modular_headers => true
  pod 'Firebase/Firestore', :modular_headers => true
  pod 'Firebase/Storage', '11.0.0'  # Add Firebase/Storage
  pod 'NMapsMap'
  pod 'GoogleMaps'

  # Install all iOS pods for Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Define the RunnerTests target
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# Post-install script to set deployment target and additional settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
